swagger: "2.0"
info:
  description: "REST access to HirPlacc datas"
  version: "1.0.0"
  title: "Swagger HirPlacc"
host: "wt-a339e6290d2b75021e179abd37d83555-0.sandbox.auth0-extend.com"
basePath: "/"
tags:
- name: "articles"
  description: "Access to Articles"
schemes:
- "https"
paths:
  /articles:
    get:
      tags:
      - "articles"
      summary: "Get articles"
      description: "Returns a bunch of articles"
      operationId: "getArticles"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Article"
  /articles/{articleId}:
    get:
      tags:
      - "articles"
      summary: "Find article by ID"
      description: "Returns a single article"
      operationId: "getArticleById"
      produces:
      - "application/json"
      parameters:
      - name: "articleId"
        in: "path"
        description: "ID of article to return"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Article"
        404:
          description: "Article not found"
definitions:
  Article:
    type: "object"
    required:
    - "_id"
    properties:
      _id:
        type: "string"
      description:
        type: "string"
      image_url:
        type: "string"
      title:
        type: "string"
      source_domain:
        type: "string"
      text:
        type: "string"
      url:
        type: "string"